repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
    - id: flake8
      exclude: ^(imagesapi/settings.py)
      additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-import-order
