version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ./run_server.sh
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      retries: 10

volumes:
  postgres_data:
